name: cogrob

dependencies:
  - python=3.8.8
  - pandas=1.2.5
  - pip
  - pip:
    - unified-planning==0.4.2.362.dev1
    - up-fast-downward==0.0.4
    - up-tamer==0.2.0.23.dev1
    - ipykernel
    - matplotlib
    - shapely
    - heapdict
    - scipy
    - gym==0.19
    - gym[toy_text]